apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cachemanager-asb
  namespace: default
  labels:
    app: cachemanager-asb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cachemanager-asb
  template:
    metadata:
      labels:
        app: cachemanager-asb
    spec:
      containers:
      - name: cachemanager-asb
        image: arqregistry.azurecr.io/cachemanager-asb-cosmosdb:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: AZURE_SERVICE_BUS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: apicore
                key: azure-service-bus-endpoint
          - name: AZURE_SERVICE_BUS_TOPIC
            valueFrom:
              secretKeyRef:
                name: apicore
                key: azure-service-bus-topic
          - name: AZURE_SERVICE_BUS_SUBSCRIPTION
            valueFrom:
              secretKeyRef:
                name: apicore
                key: azure-service-bus-subscription
          - name: API_CORE_ENDPOINT
            value: http://products.arq.customer.corp:8080/api/products
          - name: AZURE_COSMOSDB_URI
            value: https://saci-arq-cosmosdb.documents.azure.com:443/
          - name: AZURE_COSMOSDB_KEY
            valueFrom:
              secretKeyRef:
                name: apicore
                key: azure-cosmosdb-key
          - name: AZURE_COSMOSDB_DATABASE
            value: Products
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "150Mi"
      imagePullSecrets:
      - name: arqregistry
